function clearDir(dirName)

unix([...
    'rm -fr /seq/orzuk2/compressed_sensing/metagenomics/next_gen/CS/BAC/dataForSim/',dirName,...
    ' /seq/orzuk2/compressed_sensing/metagenomics/next_gen/CS/tmp/',dirName,...
     ' /seq/orzuk2/compressed_sensing/metagenomics/next_gen/CS/BAC/tmpRuns/',dirName
     ])