  rmpath(genpath('/home/csfaculty/shental/Weizmann/ph2users/fenoam/'));
  rmpath('/home/csfaculty/shental/matlab');cd ~/CS/mFilesBAC;
  addpath('~/CS/mFilesBAC');  %cd /homes/csfaculty/shental/CS/BAC/cvx; 
  mcc -v -m distributeBAC_generalOrFourth.m ...
      -d /homes/csfaculty/shental/CS/BAC/cvx -a grep.m  ...
      -a currReadsFourth.m -a findParametersReads.m ...
      -a fun_prep_data_for_simulations_loadSpecificBAC2OrFourth.m ...
      -a get_duplicates.m -a get_duplicates2.m -a getuserdir.m ...
      -a iterateParallelDistributedSequenceFilesOrFourth.m ...
      -a myHistForBAC.m -a myUniqueUINT8.m -a randi.m -a newReadsBasedSeed2Or.m ...
      -a prepareReadsForRandomSequences.m -a solveForGroupOrFourth.m ...
      -a prepareGroupOf1000DistributedSequenceFilesOrFourth  ...
      -a runOneGroupOf1000ForCompilationFourth.m -a set_solution_bounds.m ...
      -a doRepeatsFourth.m -a calcPartFourth.m -a createReadsData -a CreateMothurDistNoamL1L2.m ...
      -a CreateMothurDistNoam2.m  -a addL1toL2_res.m  ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/builtins ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/commands ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/functions ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/keywords ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/lib ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/sdpt3 ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/sedumi ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/sets ...
      -a /homes/csfaculty/shental/CS/BAC/cvx/structures



