function delDir(outFileDirName)
  
userDir = '/seq/orzuk2/compressed_sensing/metagenomics/next_gen';
disp(['del ',outFileDirName,'?'])
pause
unix(['rm -fr ',userDir,'/CS/tmp/',outFileDirName,';',...
      ';rm -fr ',userDir,'/CS/BAC/dataForSim/',outFileDirName,';',...
      ';rm -fr ',userDir,'/CS/BAC/tmpRuns/',outFileDirName,';',...
      ';rm -fr ',userDir,'/CS/BAC/',outFileDirName,';',...
      ';rmdir ',userDir,'/CS/tmp/',outFileDirName,';',...
      ';rmdir ',userDir,'/CS/BAC/dataForSim/',outFileDirName,';',...
      ';rmdir ',userDir,'/CS/BAC/tmpRuns/',outFileDirName,';',...
      ';rmdir ',userDir,'/CS/BAC/',outFileDirName,';'])


